[package]
name = "rust-opengl-example"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
gl = "0.14.0"
glutin = "0.32.1"
glutin-winit = "0.5.0"
winit = "0.30.5"

[build-dependencies]
cfg_aliases = "0.2.1"
gl_generator = "0.14.0"
